# Generated by Django 4.2 on 2023-04-11 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caregoria',
            new_name='Categoria',
        ),
    ]
